sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - 7
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run validate
